comment:
  footer:  |
    ---
    > This is an automated comment. Responding to the bot or mentioning it won't have any effect

labels:
  - name: invalid
    labeled:
      issue:
        body: |
          Hi, thanks for bringing this issue to our attention.

          Unfortunately, this issue has been marked invalid and will be closed.
          The most common reasons for marking an issue or pull request as invalid is because:

          - Contains insufficient details, it's unclear for the reviewer, or it's impossible to move forward without a lot of interaction
          - It does not respect the issue template
          - It's unrelated to the project (e.g., related to one of its libraries)
          - It does not follow the technical philosophy of the project
          - Violates our [Code of Conduct](https://github.com/krakendio/.github/blob/main/CODE_OF_CONDUCT.md)

          You can still make an edit or leave additional comments that lead to reopening this issue.

          Thanks
        action: close
      pr:
        body: |
          Hi @{{ pull_request.user.login }}, thanks for having spent the time to code and send an improvement to KrakenD.

          Unfortunately, this pull request has been marked as invalid and will be closed without merging.
          The most common reasons for marking an issue or pull request as invalid is because:

          - Contains insufficient details, it's unclear for the reviewer, or it's impossible to move forward without a lot of interaction
          - It's unrelated to the project (e.g., related to one of its libraries)
          - It does not follow the philosophy of the project
          - Violates our [Code of Conduct](https://github.com/krakendio/.github/blob/main/CODE_OF_CONDUCT.md)

          You can still make an edit or leave additional comments that lead to reopening this issue.
        action: close
  - name: wontfix
    labeled:
      issue:
        body: |
          Hi, thank you for bringing this issue to our attention.

          There are many factors that influence our product roadmaps and determine the features, fixes, and suggestions we implement.
          When making decisions about what to prioritize and work on, we combine your feedback and suggestions with insights from our development team,
          product analytics, research findings, and more.

          This information, combined with our product vision, determines what we implement and its priority order.

          Unfortunately, we don't foresee that this issue is going to progress any further in the short-medium term and we are closing it.

          While this issue is now closed, we continue to monitor requests, including this one, for our future roadmap.

          If you have additional information you would like to provide please share."
        action: close
      pr:
        body: |
          Hi @{{ pull_request.user.login }}, thanks for having spent the time to code and send an improvement to KrakenD.

          When deciding what to include in our product, we are cautious about what we add. We rarely add features, make changes that a small number of users need, or are out-of-scope of the project.

          KrakenD is used in millions of servers every year, and the slightest change has an impact. Unfortunately, sometimes we cannot evaluate the effect quickly or have the resources to face it, and we choose safety over having a specific additional feature. Sometimes, the understanding of functionality does not match the developer's thinking, which can be considered a "bug".

          Although it's never nice to reject someone's work, after evaluating your code, we think it's better not to merge it. We are doing it for all users' benefit and to keep the code's simplicity, philosophy, and maintainability.

          While this pull request is now closed, this is not a definitive decision. If you think you can provide additional information that would help us change our minds, you are free to do so."
        action: close
  - name: duplicate
    labeled:
      issue:
        body: This issue already exists.
        action: close
  - name: good first issue
    labeled:
      issue:
        body: This issue is easy for contributing. Everyone can work on this.
  - name: spam
    labeled:
      issue:
        body: |
          This issue has been **LOCKED** because of spam!

          Please do not spam messages and/or issues on the issue tracker. You may get blocked from this repository for doing so.
        action: close
        locking: lock
        lock_reason: spam
      pr:
        body: |
          This pull-request has been **LOCKED** because of spam!

          Please do not spam messages and/or pull-requests on this project. You may get blocked from this repository for doing so.
        action: close
        locking: lock
        lock_reason: spam