name: Label commenter
on:
  issues:
    types: [labeled, unlabeled]
  pull_request_target:
    types: [labeled, unlabeled]
jobs:
  stale:
    uses: krakend/.github/.github/workflows/label-commenter.yml@main
