name: 'Lock Threads'

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

concurrency:
  group: lock

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v3
        with:
          pr-inactive-days: '90'
          issue-inactive-days: '90'
          add-issue-labels: 'locked'
          issue-comment: >
            This issue was marked as resolved a long time ago and now has been
            automatically locked as there has not been any recent activity after it.
            You can still open a new issue and reference this link.
          pr-comment: >
            This pull request was marked as resolved a long time ago and now has been
            automatically locked as there has not been any recent activity after it.
            You can still open a new issue and reference this link.